2025-05-06 16:34:44,738 - trading_system.trading_system - ERROR - [trading_system.py:686] - Lỗi khi huấn luyện agent: axis 1 is out of bounds for array of dimension 0
Traceback (most recent call last):
  File "E:\AI_AGENT\automated-trading-system\trading_system.py", line 669, in train_agent
    training_history = trainer.train()
  File "E:\AI_AGENT\automated-trading-system\models\training_pipeline\trainer.py", line 242, in train
    episode_reward, episode_length, episode_losses = self._train_episode(max_steps, render_frequency)
  File "E:\AI_AGENT\automated-trading-system\models\training_pipeline\trainer.py", line 378, in _train_episode
    loss_info = self.agent.learn()
  File "E:\AI_AGENT\automated-trading-system\models\agents\dqn_agent.py", line 276, in learn
    q_target = rewards + (1 - dones) * self.gamma * np.max(q_target_next, axis=1)
  File "<__array_function__ internals>", line 180, in amax
  File "C:\Users\MAY10\anaconda3\envs\autotrading_env\lib\site-packages\numpy\core\fromnumeric.py", line 2793, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\MAY10\anaconda3\envs\autotrading_env\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
numpy.AxisError: axis 1 is out of bounds for array of dimension 0
2025-05-06 16:34:44,743 - trading_system.train_command - ERROR - [train_commands.py:327] - Huấn luyện thất bại
